name = "Spot"
uuid = "f11abc24-ce50-11e8-2475-af6658d13f2b"
repo = "https://github.com/sisl/Spot.jl"
version = "0.2.5"

[deps]
CxxWrap = "1f15a43c-97ca-5a2a-ae31-89f07a497df4"
Graphs = "86223c79-3864-5bf0-83f7-82e725a168b6"
MetaGraphs = "626554b9-1ddb-594c-aa3c-2596fe9399a5"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
Spot_julia_jll = "b9ff107b-b78e-5f57-8772-57a339630ba9"
TikzPictures = "37f6aa50-8035-52d0-81c2-5a1d08754b2d"
libcxxwrap_julia_jll = "3eaa8342-bff7-56a5-9981-c04077f7cee7"

[compat]
CxxWrap = "0.11, 0.12, 0.15, 0.16, 0.17"
Graphs = "1.5"
MetaGraphs = "0.6, 0.7"
Parameters = "0.12"
Spot_julia_jll = "2.9.7"
TikzPictures = "3.5"
julia = "1.6, 1.7, 1.8, 1.9, 1.10"
libcxxwrap_julia_jll = "0.12.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
